<footer>
    <div class="footer-content">
        <p>&copy; 2026 Lumina University. All rights reserved.</p>
        <ul class="footer-links">
            <li><a href="mailto:info@luminauniversity.com">Contact Us: info@luminauniversity.com</a></li>
            <li><a href="https://nahanparvinnavas.atlassian.net/jira/software/projects/PT1/summary" target="_blank" rel="noopener noreferrer">Project Jira Board</a></li>
            <li><a href="https://github.com/106385897/Project-Part-02.git" target="_blank" rel="noopener noreferrer">GitHub Repository</a></li>
    </div>
</footer>