<header id="main-header">
    <div class="header-container">

        <img src="images/logo.png"
             alt="Lumina University Logo"
             class="logo">

        <div class="title-group">

            <h1>Lumina University</h1>

            <h2>Department of Digital Learning & Research</h2>

            <p><em>"Illuminating the Future of Education through Digital Innovation."</em></p>

        </div>
        

    </div>
    <?php include 'nav.inc';?>
</header>
